name: Site workflow

on:
  push:
    branches:
    # Only accept deploying from the master branch
    - master

jobs:
  test:
    name: App linting/testing
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS LTS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm ci
    - name: Lint application
      run: npm run lint
#     - name: Test application
#       run: npm test
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS LTS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm ci
    - name: Generate documentation
      run: npm run genDocs
    - name: Deploy site
      run: npm run action:deploy
      env:
        # GH_TOKEN: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
