name: Site workflow

on:
  push:
    branches:
    # Only accept deploying from the master branch
    - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup NodeJS LTS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm ci
    - name: Run githubPages npm script
      run: npm run githubPages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
